name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 確保與你的主分支名稱一致

permissions:
  contents: read
  pages: write
  id-token: write

# 設定全域環境變數，強制使用 Node.js 24 以消除警告
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Firebase Config File
        run: |
          mkdir -p js
          cat << 'EOF' > js/firebaseConfig.js
          window.FIREBASE_CONFIG = ${{ secrets.FIREBASE_API_KEY }};
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
