name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 確保與你的主分支名稱一致

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Firebase Secret
        run: |
          # 它會將內容注入到 index.html 的 <head> 之後 
          sed -i 's|<head>|<head><script>window.FIREBASE_CONFIG = ${{ secrets.FIREBASE_API_KEY }};</script>|g' index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
